version: '2'
services:
  webserver:
    image: 219737062836.dkr.ecr.us-east-1.amazonaws.com/web 
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8000:8000"
    links:
      - processor
      - info
  processor:
    image: 219737062836.dkr.ecr.us-east-1.amazonaws.com/proc
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8082"
  info:
    image: 219737062836.dkr.ecr.us-east-1.amazonaws.com/info
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8092"
